class_name DriveProfiles
extends RefCounted

# v0.11: one route assembled from literal connected road chunks.
# "connector" profiles are short pieces of drivable road whose width and camera
# scale change over distance. They are not transition screens or timers.
const ORDER := [
	"neighborhood",
	"connector_out",
	"highway",
	"connector_in",
	"downtown",
	"parking_connector",
	"parking_street",
]

const BASE_SPEED := 680.0
const BASE_LANE_WIDTH := 110.0
const BASE_BLOCK_SPACING := 1900.0

const PROFILES := {
	"neighborhood": {
		"name": "NEIGHBORHOOD",
		"mode": "turn",
		"lane_count": 1,
		"car_scale": 0.78,
		"speed_scale": 0.58,
		"road_scale": 0.72,
		"block_scale": 0.55,
		"stop_signs": false,
		"auto_stop_time": 0.0,
		"one_way": false,
		"grid_size": Vector2i(4, 4),
		"entry": Vector2i(0, 3),
		"exit": Vector2i(3, 0),
		"traffic_count": 0,
		"section_length": 0.0,
		"exit_lane": -1,
		"start_lane": 0,
	},
	"connector_out": {
		"name": "CONNECTOR",
		"mode": "connector",
		"lane_count": 1,
		"car_scale": 0.78,
		"speed_scale": 0.82,
		"road_scale": 0.72,
		"to_lane_count": 4,
		"to_car_scale": 0.48,
		"to_road_scale": 0.75,
		"section_length": 2200.0,
		"traffic_count": 0,
		"exit_lane": -1,
		"start_lane": 0,
	},
	"highway": {
		"name": "HIGHWAY",
		"mode": "lane",
		"lane_count": 4,
		"car_scale": 0.48,
		"speed_scale": 1.80,
		"road_scale": 0.75,
		"block_scale": 0.0,
		"stop_signs": false,
		"auto_stop_time": 0.0,
		"one_way": false,
		"grid_size": Vector2i.ZERO,
		"entry": Vector2i.ZERO,
		"exit": Vector2i.ZERO,
		"traffic_count": 8,
		"section_length": 7600.0,
		"exit_lane": 3,
		"start_lane": 1,
	},
	"connector_in": {
		"name": "CONNECTOR",
		"mode": "connector",
		"lane_count": 1,
		"car_scale": 0.48,
		"speed_scale": 0.92,
		"road_scale": 0.75,
		"to_lane_count": 1,
		"to_car_scale": 1.05,
		"to_road_scale": 0.92,
		"section_length": 2200.0,
		"traffic_count": 0,
		"exit_lane": -1,
		"start_lane": 0,
	},
	"downtown": {
		"name": "CITY",
		"mode": "turn",
		"lane_count": 1,
		"car_scale": 1.05,
		"speed_scale": 0.68,
		"road_scale": 0.92,
		"block_scale": 0.42,
		"stop_signs": false,
		"auto_stop_time": 0.0,
		"one_way": false,
		"grid_size": Vector2i(4, 4),
		"entry": Vector2i(0, 3),
		"exit": Vector2i(3, 0),
		"traffic_count": 0,
		"section_length": 0.0,
		"exit_lane": -1,
		"start_lane": 0,
	},
	"parking_connector": {
		"name": "PARKING LANE",
		"mode": "connector",
		"lane_count": 1,
		"car_scale": 1.05,
		"speed_scale": 0.52,
		"road_scale": 0.92,
		"to_lane_count": 2,
		"to_car_scale": 1.05,
		"to_road_scale": 0.92,
		"section_length": 900.0,
		"traffic_count": 0,
		"exit_lane": -1,
		"start_lane": 0,
	},
	"parking_street": {
		"name": "PARK",
		"mode": "lane",
		"lane_count": 2,
		"car_scale": 1.05,
		"speed_scale": 0.42,
		"road_scale": 0.92,
		"block_scale": 0.0,
		"stop_signs": false,
		"auto_stop_time": 0.0,
		"one_way": false,
		"grid_size": Vector2i.ZERO,
		"entry": Vector2i.ZERO,
		"exit": Vector2i.ZERO,
		"traffic_count": 0,
		"section_length": 1900.0,
		"exit_lane": 1,
		"start_lane": 0,
		"parking_lane": 1,
	},
}


static func get_profile(profile_id: String) -> Dictionary:
	return PROFILES.get(profile_id, {})
